### ISSUE TITLE
Ghosler not working with some content ?

### ISSUE THREAD

**Issue by Wobak** [ItzNotABug/ghosler#63] opened 2024-07-01 11:46 UTC
Hello,

Following https://github.com/ItzNotABug/ghosler/issues/62#issue-2381827260 here.

It appears that it actually isn't the gallery that is the problem.

I just created a post using a feature image, pics and text, and I still got the error.
I removed the feature image, error remains.

No gallery, no feature image, just text and pics, and always the same error.

Is there a way for me to give more details?

```
ghosler  | Newsletter: Post received via webhook.
ghosler  | Newsletter: 2 users have enabled receiving newsletters.
ghosler  | Ghost: Site comments enabled: false
ghosler  | Newsletter: Error: socket hang up
ghosler  | TypeError: Cannot destructure property 'trackedLinks' of '(intermediate value)' as it is undefined.
ghosler  |     at Newsletter.send (file:///usr/src/app/utils/newsletter.js:38:17)
```

Thanks for your help !

**Comment by Wobak** [comment] 2024-07-01 13:08
In the Ghosler GUI, the error shows up like this:
```
[2024-07-01 12:56:08 UTC] => [ERROR] => Newsletter: Error: socket hang up
at connResetException (node:internal/errors:720:14)
at TLSSocket.socketCloseListener (node:_http_client:474:25)
at TLSSocket.emit (node:events:529:35)
at node:net:350:12
at TCP.done (node:_tls_wrap:657:7)
```

**Comment by ItzNotABug** [comment] 2024-07-01 13:13
Could you tell or maybe share the contents of the post? If its sensitive, you could share over [email](mailto:itznotabug@gmail.com).
As you said in the previous issue that removing the gallery component in the ghost editor helps, I am just trying to narrow down the cause of this. Something is closing the connection it seems.

1. Does the error happen if there is a post feature image and just text content?
2. Does the error happen if there's an image in the post content?

**Comment by Wobak** [comment] 2024-07-01 13:19
I will try to narrow down the issue, but that requires removing members settings because I don't want to spam them with emails. (even if they don't receive any at this stage).

I've sent you an email with the posts.

**Comment by Wobak** [comment] 2024-07-01 13:25
OK So removing all pictures from a post got it to work. I'm going to add them back and see if there's a specific one that gets it to stop working.

**Comment by Wobak** [comment] 2024-07-01 13:44
OK I think I figured out something interesting. I got it to work with pictures I inserted in the post using the + button of Ghost with the "Insert Image". It seems to stop working when I copy and paste images directy in the editor. Let me try to re-upload all the pictures in an exising post using only the + button.

**Comment by Wobak** [comment] 2024-07-05 16:58
Hello @ItzNotABug , any update on your end on this?

**Comment by ItzNotABug** [comment] 2024-07-06 04:27
> Hello @ItzNotABug , any update on your end on this?

Hey @Wobak,
I'll check this soon.

**Comment by ItzNotABug** [comment] 2024-07-06 08:02
Hey @Wobak,
Is the post link that you sent over the email is still causing an issue? I copied over the post's content and images and the render process along with other goes fine for me. Even received an email for the same post when I tested locally.

**Comment by ItzNotABug** [comment] 2024-07-06 08:32
Are there any timeouts, content max size set on your server?
Eg: timeouts or content max size limit on a NGINX like configuration.

**Comment by ItzNotABug** [comment] 2024-07-20 11:38
@Wobak any updates? were you able to solve this?

**Comment by Wobak** [comment] 2024-07-26 05:39
Hi, unfortunately I moved to a different solution that doesn't not have the same level of integration, but happy to try out a few things. 
I'm running the docker version of ghost, so no nginx as far as I'm aware, direclty nodejs. What would you like me to test ?

**Comment by ItzNotABug** [comment] 2024-09-15 07:53
Closing as I haven't been able to reproduce this. Feel free to open if the issue is reproducible.

**Closed as not planned by ItzNotABug** 2024-09-15 07:53 UTC
