### ISSUE TITLE
Issue saving changes in setting section

### ISSUE THREAD

**Issue by s4v0h34d** [ItzNotABug/ghosler#33] opened 2024-03-06 15:16 UTC
Hi and thanks for this tool. Hoping I'll manage to set it up, it's the solution to all my problems.

I've got a Ghost instance on a VPS, I installed it with Yunohost and everything worked. I installed Ghosler and everything went fine.
After I login, I click on Settings in the Manage your settings box.
I fill every field with what's needed:
- in Ghost settings i insert my API URL, my Admin Key and I generate the Secret Key by clicking on the button Click to generate Secure Key;
- in newsletter settings I leave everything as it is
- in Email Settings I click on Add New and then fill every field in the drop-down menu for Email configuration 1 (even the [optional] one), I don't change the numbers in the last two fields

and then I proceed to click on Save Changes.
Nothing happens.
If I try to go back to the Home page a red warning message appears, telling me to: "Set up your Ghost Site Url & add an Admin API Key."
I don't know what I'm doing wrong.
Sorry for bothering, if it's a simple misunderstanding, and thanks again for your work.

**Comment by ItzNotABug** [comment] 2024-03-06 16:27
Hey 👋,
I did a clean install & was able to save the settings.

Can you confirm if the error message on main index page (after saving setting) is "Set up your Ghost Site Url & add an Admin API Key." & not "Update your username and password. Default - Username: ghosler, Password: admin"

**Comment by s4v0h34d** [comment] 2024-03-06 16:43
Yes, I'm positive, I can attach a screenshot, if needed.
I already updated the password and that process went well.

Instant update (I tried to log-out and log back in and this happened):
after I updated the password, I logged out and tried to login again, and my new password didn't work. I endered "admin", and I could log in. If I try to update the password and insert "admin" as Current Password, I get an error saying "Current password not correct", but if I insert in the Current password field the password I used when updating in the previous login, the update is successful.

**Comment by ItzNotABug** [comment] 2024-03-06 16:51
Seems like something is off. Even after saving data, it didn't save which is strange. Is anything logged in the dev console when you try to save any setting?

Also could you try this in incognito mode?

**Comment by s4v0h34d** [comment] 2024-03-06 17:03
![Schermata del 2024-03-06 18-02-07](https://github.com/ItzNotABug/ghosler/assets/96574521/beb7278a-50c5-4dd4-a1c5-93387f7c2200)

If for "dev console" you mean the debug log, this is the log.
And due to cookie issues in the past, I did everything I said before in incognito mode

**Comment by ItzNotABug** [comment] 2024-03-06 17:50
Hi there, I have found the issue for this.
I will test and release a fix probably by tomorrow.

Thanks for creating this issue.

**Comment by ItzNotABug** [comment] 2024-03-06 18:31
Hey @s4v0h34d,
The issue is fixed in `0.91`.

Do a `ghosler update` to update to latest version for this fix.

**Comment by s4v0h34d** [comment] 2024-03-07 08:39
Hi @ItzNotABug ,
now the login issue is fixed, when I change the password, during the next login, the password I have to insert is the new one.
But the saving bug is still there.
I insert all data as I wrote, I click on Save Changes and nothing happens. And when I go back to the home page, the same red error message appears.

**Comment by ItzNotABug** [comment] 2024-03-07 10:22
@s4v0h34d Unable to reproduce on latest ghosler version (`0.91`). I am able to save the settings data and also update.
Please check if there isn't any identical webhook on your Ghost site. If the issue persists, try with a clean install.

**Comment by s4v0h34d** [comment] 2024-03-07 11:24
Uninstalled ghosler, uninstalled ghosler-cli, reinstalled everything, but still nothing happens when I save the settings.
Looking into the config.production.json file, I can see that the password encription changes, but nothing else gets the parameters I insert in the interface.
(and looking into it, is it right that the "mail" section doesn't list parameters? Maybe they're listed somewhere else, but I don't know how they'll be called from here. I'm just guessing, take everything I say as a shot in the dark.)
Sorry again and thanks again for your dedication

**Comment by ItzNotABug** [comment] 2024-03-07 17:53
Hey @s4v0h34d,
would you be able to share more details via email and the keys for the Ghost instance so I could see what's really happening on your Ghosler instance.

**Comment by ItzNotABug** [comment] 2024-03-10 09:57
Marking this issue resolved as there seemed to be SSL issue that was causing the `webhook` not added to Ghost. I was manually able to save all the data.

Reopen if you face the issue again.

**Closed as completed by ItzNotABug** 2024-03-10 09:57 UTC

**Comment by s4v0h34d** [comment] 2024-03-15 20:03
Hi Darshan,
sorry for my bothering you this much, but I found out what the problem 
was:
I installed ghost using yunohost (it's like docker, but "more open 
oriented".
This caused the port where ghosler works to be considered "external" to 
the site, so the let's encrypt certificate didn't work.
I found out a way to make the port "visible" to yunohost: you need to 
install an app from the younohost catalog called Redirect, that works as 
a reverse-proxy, make it point to an internal ip 127.0..0.1:2369/login 
and the ghosler login page appears.
The problem is that once you login, you're redirected to younohost's 
panel, not to ghostler's page. How could this be solved?
If you're interested in helping future yunohost users use your software, 
I could help you writing the step by step documentation.
Thanks again and keep up the great work
s

Il 10.03.2024 10:57 Darshan ha scritto:

**Comment by ItzNotABug** [comment] 2024-03-16 03:58
Hey @s4v0h34d,
Does this help - https://forum.yunohost.org/t/how-to-stop-non-registered-sub-domains-from-redirecting-to-admin-interface/3186/10?

**Comment by s4v0h34d** [comment] 2024-03-21 15:58
Hi Darshan,
great news, your link was a good solution, but we found a better one, 
where we don't have to change anything in the yunohost settings.
Now everything works with the Redirect app on a subdomain, pointing to 
the internal server as a reverse proxy, the ghosler interface appears, 
it's updated with all new settings and I can see the webhook in the 
Ghost interface.
The only problem, now, is that when I post something, no mail is sent.
I can see the post appear in the analytics page of ghosler, but it 
appears that no mail is sent. In the log section it appears nothing's 
wrong with the sending:
[2024-03-21 14:02:33 UTC] => [DEBUG] => Newsletter: Email sending 
complete.
[2024-03-21 14:02:33 UTC] => [DEBUG] => Newsletter: Single user or email 
config found, sending email(s).
[2024-03-21 14:02:33 UTC] => [DEBUG] => Newsletter: Initializing sending 
emails.
[2024-03-21 14:02:33 UTC] => [DEBUG] => Newsletter: 2 users have enabled 
receiving newsletters.
[2024-03-21 14:02:33 UTC] => [DEBUG] => Newsletter: Post received via 
webhook.
I don't know what I'm missing, I hope it's something easy, so I won't 
take anymore of your time.
Thanks and sorry again (we're getting there! I'll write to you with the 
yunohost solution as soon as everything works!)
bye
s


Il 16.03.2024 04:59 Darshan ha scritto:

**Comment by ItzNotABug** [comment] 2024-03-22 13:17
Hey @s4v0h34d,
Could you please create a new issue. This one is pretty old and has its initial issue already fixed.

Thanks.

**Comment by s4v0h34d** [comment] 2024-03-22 13:23
Hi!
Yes! I'll do it right away.
Thanks and sorry
s

Il 22.03.2024 14:18 Darshan ha scritto:
